import {
  ActivityTimeseriesPoint,
  AggregateDemographics,
  BridgeKOL,
  BurstAlert,
  CanonicalPost,
  ConnectorInfo,
  ConversationThread,
  CrossSegmentDiffusionReport,
  DynamicTopic,
  HealthResponse,
  InfluencerAudienceProfile,
  KOLProfile,
  NarrativeDriftAlert,
  NetworkOverview,
  TemporalSentimentPoint,
  TimelineBounds,
  TrendForecast,
  UserProfile,
} from '../types';

export const mockHealth: HealthResponse = {
  status: 'ok',
  version: '0.1.0',
  engines: {
    duckdb: 'online',
    timeline: 'online',
    nlp: 'online',
    demographics: 'online',
    trends: 'online',
    network: 'online',
    connectors: '5 registered',
    orchestrator: 'online',
    broadcaster: 'online',
  },
};

export const mockTimelineBounds: TimelineBounds = {
  earliest: '2026-09-01T00:00:00Z',
  latest: '2026-09-16T18:30:00Z',
  total_posts: 12480,
};

export const mockPosts: CanonicalPost[] = [
  {
    id: 'post_101',
    platform: 'twitter',
    author_id: 'user_alex_ai',
    author_screen_name: 'alex_researcher',
    text: 'Breakthrough in open-weights reasoning models! The latency reduction and edge quantization performance are astonishing. #AI #MachineLearning',
    timestamp: '2026-09-16T17:45:00Z',
    urls: ['https://arxiv.org/abs/2609.12345'],
    hashtags: ['AI', 'MachineLearning', 'OpenSource'],
    mentions: ['neuro_lab', 'deeptech'],
    media_urls: [],
    metrics: { likes: 1420, reposts: 380, replies: 94, quotes: 45, impressions: 42000 },
  },
  {
    id: 'post_102',
    platform: 'telegram',
    author_id: 'channel_crypto_pulse',
    author_screen_name: 'CryptoAlphaPulse',
    text: 'Decentralized compute networks see a 300% surge in daily active nodes following the protocol upgrade. Community sentiment is at an all-time high.',
    timestamp: '2026-09-16T17:15:00Z',
    urls: ['https://t.me/CryptoAlphaPulse/842'],
    hashtags: ['Web3', 'DeFi', 'Compute'],
    mentions: [],
    media_urls: [],
    metrics: { likes: 890, reposts: 215, replies: 62, quotes: 12, views: 18500 },
  },
  {
    id: 'post_103',
    platform: 'youtube',
    author_id: 'user_tech_review',
    author_screen_name: 'SiliconDeepDive',
    text: 'Full architectural breakdown: how modern local LLMs run on consumer hardware with sub-5ms token generation. Check pinned comment for benchmarks!',
    timestamp: '2026-09-16T16:50:00Z',
    urls: ['https://youtube.com/watch?v=mock_video_id'],
    hashtags: ['Hardware', 'AI', 'TechReview'],
    mentions: [],
    media_urls: [],
    metrics: { likes: 3200, reposts: 410, replies: 312, quotes: 0, views: 87400 },
  },
  {
    id: 'post_104',
    platform: 'reddit',
    author_id: 'user_kernel_dev',
    author_screen_name: 'r/LocalLLaMA_dev',
    text: 'Oh great, another benchmark claiming 10x speedup with zero code changes... until you read footnote 4 where batch size was set to 1. Groundbreaking! 🙄',
    timestamp: '2026-09-16T16:20:00Z',
    urls: ['https://reddit.com/r/LocalLLaMA/comments/mock'],
    hashtags: ['Benchmarks', 'RealityCheck'],
    mentions: [],
    media_urls: [],
    metrics: { likes: 654, reposts: 82, replies: 145, quotes: 28 },
  },
  {
    id: 'post_105',
    platform: 'bluesky',
    author_id: 'did:plc:mock_user_sarah',
    author_screen_name: 'sarah_data.bsky.social',
    text: 'Privacy-preserving AI pipelines are no longer just an academic curiosity. Regulatory clarity in 2026 makes anonymization protocols a core business mandate.',
    timestamp: '2026-09-16T15:40:00Z',
    urls: [],
    hashtags: ['DataPrivacy', 'Compliance', 'AI'],
    mentions: [],
    media_urls: [],
    metrics: { likes: 520, reposts: 140, replies: 33, quotes: 19 },
  },
  {
    id: 'post_106',
    platform: 'twitter',
    author_id: 'user_dr_elena',
    author_screen_name: 'dr_elena_climate',
    text: 'Solar and battery grid storage just crossed 45% of peak daytime supply across southern regions. Massive engineering milestone!',
    timestamp: '2026-09-16T14:10:00Z',
    urls: [],
    hashtags: ['CleanEnergy', 'ClimateTech', 'Innovation'],
    mentions: ['CleanGrid_Org'],
    media_urls: [],
    metrics: { likes: 2150, reposts: 640, replies: 118, quotes: 88, impressions: 59000 },
  },
];

export const mockTimeseries: ActivityTimeseriesPoint[] = [
  { bucket: '00:00', post_count: 142 },
  { bucket: '02:00', post_count: 98 },
  { bucket: '04:00', post_count: 65 },
  { bucket: '06:00', post_count: 110 },
  { bucket: '08:00', post_count: 340 },
  { bucket: '10:00', post_count: 780 },
  { bucket: '12:00', post_count: 1050 },
  { bucket: '14:00', post_count: 1290 },
  { bucket: '16:00', post_count: 1640 },
  { bucket: '18:00', post_count: 1820 },
  { bucket: '20:00', post_count: 1450 },
  { bucket: '22:00', post_count: 890 },
];

export const mockTemporalSentiment: TemporalSentimentPoint[] = [
  {
    bucket: '08:00',
    post_count: 340,
    mean_sentiment_score: 0.35,
    positive_ratio: 0.55,
    negative_ratio: 0.15,
    neutral_ratio: 0.30,
    sarcasm_rate: 0.08,
    mean_irony_score: 0.22,
    dominant_emotion: 'optimism',
  },
  {
    bucket: '10:00',
    post_count: 780,
    mean_sentiment_score: 0.42,
    positive_ratio: 0.62,
    negative_ratio: 0.12,
    neutral_ratio: 0.26,
    sarcasm_rate: 0.06,
    mean_irony_score: 0.18,
    dominant_emotion: 'excitement',
  },
  {
    bucket: '12:00',
    post_count: 1050,
    mean_sentiment_score: 0.28,
    positive_ratio: 0.48,
    negative_ratio: 0.22,
    neutral_ratio: 0.30,
    sarcasm_rate: 0.14,
    mean_irony_score: 0.35,
    dominant_emotion: 'surprise',
  },
  {
    bucket: '14:00',
    post_count: 1290,
    mean_sentiment_score: -0.05,
    positive_ratio: 0.32,
    negative_ratio: 0.38,
    neutral_ratio: 0.30,
    sarcasm_rate: 0.24,
    mean_irony_score: 0.52,
    dominant_emotion: 'anxiety',
  },
  {
    bucket: '16:00',
    post_count: 1640,
    mean_sentiment_score: 0.25,
    positive_ratio: 0.51,
    negative_ratio: 0.21,
    neutral_ratio: 0.28,
    sarcasm_rate: 0.11,
    mean_irony_score: 0.29,
    dominant_emotion: 'joy',
  },
  {
    bucket: '18:00',
    post_count: 1820,
    mean_sentiment_score: 0.48,
    positive_ratio: 0.68,
    negative_ratio: 0.10,
    neutral_ratio: 0.22,
    sarcasm_rate: 0.05,
    mean_irony_score: 0.15,
    dominant_emotion: 'optimism',
  },
];

export const mockDemographics: AggregateDemographics = {
  total_users_profiled: 8450,
  top_countries: [
    { country: 'United States', count: 3240, percentage: 38.3 },
    { country: 'United Kingdom', count: 1220, percentage: 14.4 },
    { country: 'Germany', count: 890, percentage: 10.5 },
    { country: 'India', count: 810, percentage: 9.6 },
    { country: 'Canada', count: 620, percentage: 7.3 },
    { country: 'France', count: 480, percentage: 5.7 },
  ],
  top_cities: [
    { city: 'San Francisco, CA', count: 980, percentage: 11.6 },
    { city: 'London, UK', count: 840, percentage: 9.9 },
    { city: 'New York, NY', count: 720, percentage: 8.5 },
    { city: 'Berlin, DE', count: 490, percentage: 5.8 },
    { city: 'Bengaluru, IN', count: 450, percentage: 5.3 },
  ],
  top_languages: [
    { language: 'English', count: 6100, percentage: 72.2 },
    { language: 'German', count: 780, percentage: 9.2 },
    { language: 'Spanish', count: 590, percentage: 7.0 },
    { language: 'French', count: 420, percentage: 5.0 },
    { language: 'Others', count: 560, percentage: 6.6 },
  ],
  persona_distribution: {
    'Tech & AI': 3450,
    'Finance & Crypto': 1890,
    'Creative Arts & Design': 1210,
    'Media & Journalism': 980,
    'Healthcare & Bio': 540,
    'Academic & Science': 380,
  },
  age_distribution: {
    '<18': 420,
    '18-24': 1980,
    '25-34': 3650,
    '35-49': 1720,
    '50-64': 540,
    '65+': 140,
  },
};

export const mockProfiledUsers: UserProfile[] = [
  {
    user_id: 'user_alex_ai',
    screen_name: 'alex_researcher',
    inferred_age_bracket: '25-34',
    age_confidence: 0.92,
    detected_locations: ['San Francisco, CA', 'Bay Area'],
    normalized_country: 'United States',
    normalized_city: 'San Francisco',
    detected_languages: ['English'],
    primary_persona: 'Tech & AI',
    persona_scores: { 'Tech & AI': 0.94, 'Academic & Science': 0.65, 'Finance & Crypto': 0.22 },
    top_interests: ['Neural Networks', 'Distributed Systems', 'Open Source'],
    post_count: 432,
  },
  {
    user_id: 'user_dr_elena',
    screen_name: 'dr_elena_climate',
    inferred_age_bracket: '35-49',
    age_confidence: 0.88,
    detected_locations: ['London, UK'],
    normalized_country: 'United Kingdom',
    normalized_city: 'London',
    detected_languages: ['English', 'German'],
    primary_persona: 'Academic & Science',
    persona_scores: { 'Academic & Science': 0.91, 'Tech & AI': 0.45, 'Media & Journalism': 0.38 },
    top_interests: ['Climate Tech', 'Grid Transition', 'Renewables'],
    post_count: 289,
  },
  {
    user_id: 'user_marcus_fx',
    screen_name: 'marcus_macro',
    inferred_age_bracket: '35-49',
    age_confidence: 0.85,
    detected_locations: ['New York, NY'],
    normalized_country: 'United States',
    normalized_city: 'New York',
    detected_languages: ['English'],
    primary_persona: 'Finance & Crypto',
    persona_scores: { 'Finance & Crypto': 0.93, 'Media & Journalism': 0.41 },
    top_interests: ['Macroeconomics', 'Fintech', 'Liquid Assets'],
    post_count: 512,
  },
];

export const mockInfluencerAudience: InfluencerAudienceProfile = {
  influencer_id: 'alex_researcher',
  total_followers_analyzed: 4200,
  min_group_size: 5,
  privacy_filter_active: true,
  age_distribution: {
    '18-24': 1120,
    '25-34': 2280,
    '35-49': 680,
    '50+': 120,
  },
  top_personas: [
    { persona: 'Tech & AI Developers', count: 2150, percentage: 51.2 },
    { persona: 'University Researchers', count: 980, percentage: 23.3 },
    { persona: 'Product & Founders', count: 640, percentage: 15.2 },
    { persona: 'Venture Capital', count: 430, percentage: 10.3 },
  ],
  geo_concentration: [
    { location: 'United States (West Coast)', count: 1840, percentage: 43.8 },
    { location: 'Western Europe', count: 1050, percentage: 25.0 },
    { location: 'India & Southeast Asia', count: 750, percentage: 17.8 },
    { location: 'Canada', count: 320, percentage: 7.6 },
  ],
  activity_tiers: {
    'Highly Active (Daily)': 1890,
    'Regular (Weekly)': 1540,
    'Occasional (Monthly)': 770,
  },
};

export const mockBurstAlerts: BurstAlert[] = [
  {
    term: '#LocalAI',
    current_count: 485,
    baseline_mean: 42.1,
    baseline_std: 12.4,
    z_score: 5.82,
    is_burst: true,
    window_end: '2026-09-16T18:00:00Z',
  },
  {
    term: '#QuantumFlaws',
    current_count: 312,
    baseline_mean: 28.6,
    baseline_std: 9.8,
    z_score: 4.41,
    is_burst: true,
    window_end: '2026-09-16T18:00:00Z',
  },
  {
    term: 'edge_quantization',
    current_count: 220,
    baseline_mean: 35.0,
    baseline_std: 11.2,
    z_score: 3.25,
    is_burst: true,
    window_end: '2026-09-16T18:00:00Z',
  },
  {
    term: 'clean_grid_2026',
    current_count: 178,
    baseline_mean: 31.2,
    baseline_std: 10.5,
    z_score: 2.89,
    is_burst: true,
    window_end: '2026-09-16T18:00:00Z',
  },
];

export const mockDynamicTopics: DynamicTopic[] = [
  {
    topic_id: 1,
    name: 'Foundation Models & Quantized Inference',
    top_words: [
      { word: 'model', weight: 0.92 },
      { word: 'quantization', weight: 0.84 },
      { word: 'latency', weight: 0.78 },
      { word: 'open_weights', weight: 0.72 },
      { word: 'inference', weight: 0.69 },
    ],
    doc_count: 1840,
  },
  {
    topic_id: 2,
    name: 'Clean Grid & Renewable Storage Transitions',
    top_words: [
      { word: 'storage', weight: 0.88 },
      { word: 'battery', weight: 0.81 },
      { word: 'solar', weight: 0.76 },
      { word: 'grid', weight: 0.73 },
      { word: 'capacity', weight: 0.65 },
    ],
    doc_count: 1120,
  },
  {
    topic_id: 3,
    name: 'Decentralized Compute & Network Protocols',
    top_words: [
      { word: 'nodes', weight: 0.89 },
      { word: 'compute', weight: 0.82 },
      { word: 'protocol', weight: 0.75 },
      { word: 'decentralized', weight: 0.71 },
      { word: 'validators', weight: 0.64 },
    ],
    doc_count: 890,
  },
];

export const mockTrendForecasts: TrendForecast[] = [
  {
    term: '#LocalAI',
    velocity: 28.5,
    acceleration: 4.8,
    lifecycle_state: 'VIRAL_SURGE',
    virality_potential_score: 0.94,
    author_diversity_ratio: 0.86,
    recent_volumes: [35, 92, 210, 485],
  },
  {
    term: 'edge_quantization',
    velocity: 14.2,
    acceleration: 2.3,
    lifecycle_state: 'EMERGING',
    virality_potential_score: 0.78,
    author_diversity_ratio: 0.79,
    recent_volumes: [20, 45, 110, 220],
  },
  {
    term: '#QuantumFlaws',
    velocity: 22.1,
    acceleration: -1.2,
    lifecycle_state: 'PEAKING',
    virality_potential_score: 0.68,
    author_diversity_ratio: 0.72,
    recent_volumes: [80, 195, 340, 312],
  },
  {
    term: 'fintech_ai_agents',
    velocity: 6.4,
    acceleration: -0.8,
    lifecycle_state: 'DECELERATING',
    virality_potential_score: 0.42,
    author_diversity_ratio: 0.64,
    recent_volumes: [140, 130, 115, 95],
  },
];

export const mockNarrativeDrift: NarrativeDriftAlert = {
  term: 'Quantum Computing Encryption',
  drift_detected: true,
  cosine_distance: 0.64,
  sentiment_inverted: true,
  baseline_sentiment: 0.45, // previously optimistic
  current_sentiment: -0.38, // shifted anxious/negative
  drift_magnitude: 0.83,
};

export const mockKOLs: KOLProfile[] = [
  {
    user_id: 'user_alex_ai',
    screen_name: 'alex_researcher',
    composite_influence_score: 0.96,
    pagerank: 0.042,
    in_degree: 1420,
    out_degree: 310,
    betweenness_centrality: 0.038,
    community_id: 1, // Tech Community
  },
  {
    user_id: 'user_dr_elena',
    screen_name: 'dr_elena_climate',
    composite_influence_score: 0.89,
    pagerank: 0.035,
    in_degree: 1150,
    out_degree: 280,
    betweenness_centrality: 0.041,
    community_id: 2, // Climate/Science Community
  },
  {
    user_id: 'user_marcus_fx',
    screen_name: 'marcus_macro',
    composite_influence_score: 0.84,
    pagerank: 0.029,
    in_degree: 920,
    out_degree: 195,
    betweenness_centrality: 0.025,
    community_id: 3, // Finance Community
  },
  {
    user_id: 'user_sarah_bridge',
    screen_name: 'sarah_tech_policy',
    composite_influence_score: 0.81,
    pagerank: 0.026,
    in_degree: 860,
    out_degree: 410,
    betweenness_centrality: 0.062, // High boundary-spanner!
    community_id: 1,
  },
];

export const mockBridgeKOLs: BridgeKOL[] = [
  {
    user_id: 'user_sarah_bridge',
    screen_name: 'sarah_tech_policy',
    betweenness_centrality: 0.062,
    cross_community_ratio: 0.74,
    home_community: 1, // Tech
    connected_communities: [1, 2, 3], // Bridges Tech, Climate, and Finance!
    total_neighbors: 450,
  },
  {
    user_id: 'user_david_investor',
    screen_name: 'david_deeptech_vc',
    betweenness_centrality: 0.049,
    cross_community_ratio: 0.65,
    home_community: 3, // Finance
    connected_communities: [1, 3],
    total_neighbors: 320,
  },
];

export const mockNetworkOverview: NetworkOverview = {
  total_nodes: 7250,
  total_edges: 18450,
  density: 0.0035,
  community_count: 6,
  top_kols: mockKOLs,
};

export const mockConversationThread: ConversationThread = {
  conversation_id: 'post_101',
  metrics: {
    total_posts: 18,
    total_replies: 17,
    max_depth: 4,
    avg_branching_factor: 2.1,
    participant_count: 14,
    participant_ids: ['user_alex_ai', 'reply_1', 'reply_2', 'reply_3', 'reply_4'],
    duration_seconds: 14400, // 4 hours
    mean_reply_latency_seconds: 480, // 8 mins
    depth_distribution: { '0': 1, '1': 6, '2': 7, '3': 3, '4': 1 },
  },
  sentiment_dynamics: {
    root_post_id: 'post_101',
    root_polarity: 'positive',
    root_sentiment_score: 0.82,
    root_primary_emotion: 'excitement',
    comment_mean_sentiment: 0.44,
    polarity_drift: -0.38,
    controversy_index: 0.18,
    hostility_velocity: 0.02,
    supportive_ratio: 0.72,
    against_ratio: 0.12,
    neutral_ratio: 0.16,
    dominant_thread_emotion: 'optimism',
    emotional_trajectory: [
      { depth: 0, primary_emotion: 'excitement', polarity_score: 0.82 },
      { depth: 1, primary_emotion: 'optimism', polarity_score: 0.65 },
      { depth: 2, primary_emotion: 'surprise', polarity_score: 0.38 },
      { depth: 3, primary_emotion: 'anxiety', polarity_score: -0.15 },
    ],
  },
  thread_tree: {
    post_id: 'post_101',
    author_id: 'alex_researcher',
    text: 'Breakthrough in open-weights reasoning models! The latency reduction and edge quantization performance are astonishing. #AI #MachineLearning',
    timestamp: '2026-09-16T17:45:00Z',
    depth: 0,
    sentiment: 'positive',
    replies: [
      {
        post_id: 'post_101_r1',
        author_id: 'quant_engineer',
        text: 'Tested the 4-bit weights locally on an M4 Mac. Getting 75 tokens/sec with near zero perplexity loss! Incredible work.',
        timestamp: '2026-09-16T17:52:00Z',
        depth: 1,
        sentiment: 'positive',
        replies: [
          {
            post_id: 'post_101_r1_1',
            author_id: 'dev_sarah',
            text: 'Are you using native Metal kernels or standard llama.cpp runtime?',
            timestamp: '2026-09-16T17:58:00Z',
            depth: 2,
            sentiment: 'neutral',
            replies: [],
          },
        ],
      },
      {
        post_id: 'post_101_r2',
        author_id: 'skeptic_sysadmin',
        text: 'Wait until you see the memory bandwidth degradation under concurrent multi-user load though.',
        timestamp: '2026-09-16T18:04:00Z',
        depth: 1,
        sentiment: 'negative',
        replies: [
          {
            post_id: 'post_101_r2_1',
            author_id: 'alex_researcher',
            text: 'Paged attention with vLLM handles concurrency seamlessly now. Tested up to 64 streams without throttling.',
            timestamp: '2026-09-16T18:12:00Z',
            depth: 2,
            sentiment: 'positive',
            replies: [],
          },
        ],
      },
    ],
  },
};

export const mockDiffusionReport: CrossSegmentDiffusionReport = {
  cascade_id: 'cascade_ai_breakthrough',
  segment_by: 'community',
  total_events: 145,
  structural_virality_wiener: 3.42,
  propagation_depth: 6,
  half_life_seconds: 3200,
  adoption_timeline: [
    { segment: 'Core Tech & AI (Community 1)', user_id: 'alex_researcher', seconds_since_origin: 0, sentiment_score: 0.85, effective_polarity: 'positive' },
    { segment: 'Core Tech & AI (Community 1)', user_id: 'quant_engineer', seconds_since_origin: 420, sentiment_score: 0.78, effective_polarity: 'positive' },
    { segment: 'Bridge: Tech Policy (Community 1/2)', user_id: 'sarah_tech_policy', seconds_since_origin: 1100, sentiment_score: 0.62, effective_polarity: 'positive' },
    { segment: 'Climate & Science (Community 2)', user_id: 'dr_elena_climate', seconds_since_origin: 2450, sentiment_score: 0.54, effective_polarity: 'positive' },
    { segment: 'Bridge: Tech VC (Community 1/3)', user_id: 'david_deeptech_vc', seconds_since_origin: 3900, sentiment_score: 0.71, effective_polarity: 'positive' },
    { segment: 'Finance & Markets (Community 3)', user_id: 'marcus_macro', seconds_since_origin: 5200, sentiment_score: 0.40, effective_polarity: 'positive' },
    { segment: 'General Public / Broader Social', user_id: 'user_enthusiast_99', seconds_since_origin: 7800, sentiment_score: 0.15, effective_polarity: 'neutral' },
  ],
};

export const mockConnectors: Record<string, ConnectorInfo> = {
  twitter: {
    platform: 'twitter',
    enabled: true,
    connected: true,
    requests_recorded: 1840,
    max_requests_per_minute: 60,
  },
  telegram: {
    platform: 'telegram',
    enabled: true,
    connected: true,
    requests_recorded: 720,
    max_requests_per_minute: 30,
  },
  youtube: {
    platform: 'youtube',
    enabled: true,
    connected: true,
    requests_recorded: 450,
    max_requests_per_minute: 15,
  },
  reddit: {
    platform: 'reddit',
    enabled: true,
    connected: true,
    requests_recorded: 960,
    max_requests_per_minute: 45,
  },
  bluesky: {
    platform: 'bluesky',
    enabled: true,
    connected: true,
    requests_recorded: 1210,
    max_requests_per_minute: 120,
  },
};
